version: '3'
services:
  test-minecraft:
    image: itzg/minecraft-server
    container_name: MC
    ports:
      - 25575:25575
      - 25565:25565
    environment:
      - TYPE=FORGE
      - VERSION=1.12.2
      - FORGEVERSION=14.23.5.2838
      - EULA=TRUE
      - MEMORY=2G
    volumes:
      - '$PWD/services/API/minecraft:/data'     
    stdin_open: true
    restart: unless-stopped